server.port=8080

spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/grupo24
spring.datasource.username=grupo24_user
spring.datasource.password=G24@Qw8#Lm2!Rt7$Px9V
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.enabled=false

spring.application.name=backend-web